<?php
/**
 * This file is part of the TeamNeustaGmbH/m2t3 package.
 *
 * Copyright (c) 2017 neusta GmbH | Ein team neusta Unternehmen
 *
 * For the full copyright and license information, please view the LICENSE file that was distributed with this source code.
 *
 * @license https://opensource.org/licenses/BSD-3-Clause  BSD-3-Clause License
 */

declare(strict_types = 1);

namespace TeamNeustaGmbH\M2T3\Sso\Service;

/**
 * Class AuthenticationService
 *
 * @package TeamNeustaGmbH\M2T3\Sso\Service
 */
class AuthenticationService extends \TYPO3\CMS\Sv\AuthenticationService
{

    /**
     * magentoService
     *
     * @var MagentoService
     */
    protected $magentoService;

    /**
     * init
     *
     * @codeCoverageIgnore
     * @return bool
     */
    public function init() :bool
    {
        $this->injectMagentoService(new MagentoService());

        return parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * injectMagentoService
     *
     * @param \TeamNeustaGmbH\M2T3\Sso\Service\MagentoService $magentoService
     * @return void
     */
    public function injectMagentoService(MagentoService $magentoService)
    {
        $this->magentoService = $magentoService;
    }

    /**
     * Authenticate a user (Check various conditions for the user that might invalidate its authentication, eg. password match, domain, IP, etc.)
     *
     * @param array $user Data of user.
     * @return int >= 200: User authenticated successfully.
     *                     No more checking is needed by other auth services.
     *             >= 100: User not authenticated; this service is not responsible.
     *                     Other auth services will be asked.
     *             > 0:    User authenticated successfully.
     *                     Other auth services will still be asked.
     *             <= 0:   Authentication failed, no more checking needed
     *                     by other auth services.
     */
    public function authUser(array $user) :int
    {
        $ok = 0;
        if ($this->magentoService->getUser()) {
            $ok = 200;
        }

        return $ok;
    }


    /**
     * getUser
     *
     * @return array
     */
    public function getUser() :array
    {
        return $this->magentoService->getUser();
    }
}
